CREATE TABLE IF NOT EXISTS "GREETINGS"("ID" SERIAL PRIMARY KEY NOT NULL,"TEXT" VARCHAR NOT NULL);
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-1, 'Penny')
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-2, 'Sheldon')
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-3, 'Amy')
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-4, 'Leonard')
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-5, 'Bernadette')
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-6, 'Raj')
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-7, 'Howard')
INSERT INTO "GREETINGS"("ID", "TEXT") VALUES (-8, 'Priya')